Businesses/urls.py
from django.urls import path
from. import views

urlpatterns = [
    path('', views.index, name="home"),
    path('<int:client_id>/', views.cliente, name='cliente'),
]

Tribu/urls.py
from django.contrib import admin
from django.urls import path, include
from Businesses import views
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index) ,
    path('reajuste/', include('Compensacoes.urls')),
    path('clientes/', include('Businesses.urls')),
]

Businesses/models.py
from django.db import models

# Create your models here.
class Businesses(models.Model):
    name = models.CharField('Nome Fantasia', max_length=200)
    cnpj = models.CharField('CNPJ', max_length = 200)
    razao_social = models.CharField('Razão Social', max_length = 200)
    endereco = models.CharField('Endereço', max_length = 200)
    telefone = models.CharField('Telefone', max_length = 200)
    email = models.EmailField('E-mail', max_length=254)

Compensacoes/models.py
from django.db import models
from Businesses.models import *
from .models import *

# Create your models here.
class Compensations(models.Model):
    name = models.CharField('Compensação', max_length=200)
    date_start = models.DateField('Data de início')
    date_end = models.DateField('Data fim')
    cliente = models.ForeignKey(Businesses, on_delete=models.CASCADE)
    tipo = models.ForeignKey("CompensationTypes", on_delete=models.CASCADE)
    pdf = models.FileField(upload_to='compensacoes')

    def __str__(self):
        return self.name

class CompensationTypes(models.Model):
    name = models.CharField('Tipo de compensação', max_length=200)

class Selic(models.Model):
    value = models.DecimalField('Valor', max_digits = 12, decimal_places = 2)
    period = models.DateField('Período')

Businesses/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import *
# Create your views here.
def index(request):
    clientes = Businesses.objects.all()
    context = {'clientes': clientes}
    return render(request, 'businesses/home.html', context)

def cliente(request, client_id):
    try:
        cliente = Businesses.objects.get(id = client_id)
    except:
        return render(request, 'businesses/home.html', context)

    context = {'cliente': cliente}
    return render(request, 'businesses/cliente.html', context)

templates/businesses/cliente.html
{% extends 'base.html' %}

{% block content %}
<h2>Cliente</h2>

<div class="table-responsive">
    <table class="table">
        <tr>
            <td>Nome Fantasia</td>
            <td>{{cliente.name}}</td>
        </tr>
        <tr>
            <td>Razão Social</td>
            <td>{{cliente.razao_social}}</td>
        </tr>
        <tr>
            <td>CNPJ</td>
            <td>{{cliente.cnpj}}</td>
        </tr>
        <tr>
            <td>Endereço</td>
            <td>{{cliente.endereco}}</td>
        </tr>
        <tr>
            <td>Telefone</td>
            <td>{{cliente.telefone}}</td>
        </tr>
        <tr>
            <td>Email</td>
            <td>{{cliente.email}}</td>
        </tr>
    </table>
</div>
{% endblock %}

templates/businesses/home.html
{% extends 'base.html' %} 

{% block content %} 
<div class="table-responsive">
	<table class="table table-striped">
		<tr>
			<th>Nome</th>
            <th>Compensações</th>
		</tr>
		{% for cliente in clientes %}
		<tr>
            <td><a href="{% url 'cliente' cliente.id %}" target="_blank">{{ cliente.name }}</a></td>
            <td>
            {% for compensation in cliente.compensations_set.all %}
            <a href="{% url 'pdf' compensation.id %}">{{ compensation.name }}</a>
		    {% if compensation != cliente.compensations_set.last %}
		    ,
		    {% endif %}
            {% endfor %}
	    </td>
        </tr>
		{% endfor %}
	</table>
</div>
{% endblock content %}